version: '3.1'
networks:
  rollertempo_postgresql:
    external: false

services:
  db-server:
    container_name: rollertempo_postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: rollertempo
      POSTGRES_PASSWORD: secret
    networks:
      - rollertempo_postgresql
    volumes:
      - ${PSQL_DATA_DIR}:/var/lib/postgresql/data