name: Run Tests and Notify via Discord

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start Docker service
        run: cd ./docker && ./service.sh up
      - name: Run Go server
        working-directory: ./app/server
        run: go run . &
      - name: Run Tests
        working-directory: ./app/server/tests
        run: go test
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'